CreateUsersTable: create table `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `email_verified_at` timestamp null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateUsersTable: alter table `users` add unique `users_email_unique`(`email`)
CreatePasswordResetsTable: create table `password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePasswordResetsTable: alter table `password_resets` add index `password_resets_email_index`(`email`)
CreateFailedJobsTable: create table `failed_jobs` (`id` bigint unsigned not null auto_increment primary key, `connection` text not null, `queue` text not null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp default CURRENT_TIMESTAMP not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateClientsTable: create table `clients` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `imported_id` int not null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateDealsTable: create table `deals` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `imported_id` int not null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateTransactionsTable: create table `transactions` (`id` int unsigned not null auto_increment primary key, `hour` timestamp not null, `deal_id` int unsigned not null, `client_id` int unsigned not null, `accepted` int not null, `refused` int not null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateTransactionsTable: alter table `transactions` add constraint `transactions_deal_id_foreign` foreign key (`deal_id`) references `deals` (`id`)
CreateTransactionsTable: alter table `transactions` add constraint `transactions_client_id_foreign` foreign key (`client_id`) references `clients` (`id`)
